challange2/task/src/apps/account/urls.py
from django.urls import path

from .forms import CustomUserForm
from .views import *

from django_registration.backends.one_step.views import RegistrationView

#url patterns for user auth operations
urlpatterns = [
    path('login/', CustomLoginView.as_view(success_url='/accounts/profile/'), name='login'),
    # path('', include('django.contrib.auth.urls')),
    path('one_step_register/', RegistrationView.as_view(
            form_class=CustomUserForm,
            success_url='/accounts/profile/'),
            name='django_registration_register'),
    path('profile/', ProfileView.as_view(),
            name='profile_page',),
]

challange2/task/src/apps/payments/urls.py
from django.urls import path
from . import views

#urls pattern for intregration of stripe
urlpatterns = [
    path('', views.StripePurchasePage.as_view()), # initial page render /stripe/
    path('config/', views.stripe_config), #config for payment page /stripe/config/
    path('cancel_sub/', views.cancel_sub, name = "cancel_sub"), #url for cancelling subscription /stripe/cancel_sub/
    path('checkout_session/', views.create_checkout_session),
    path('success', views.SuccessView.as_view()), #url to redirect after successful stripe payment
    path('cancelled/', views.CancelledView.as_view()), #url to redirect after cancelled stripe payment
    path('cancellation_confirmed/', views.CancellationConfirmed.as_view()), #url to redirect after cancelling subscription
]

challange2/task/task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('stripe/',  include(("src.apps.payments.urls", "payments"), namespace='payments')),
    path('accounts/', include(("src.apps.account.urls", "account"), namespace='account')),
]

challange2/task/src/apps/account/models.py
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import AbstractUser

# custom user model to override the django registration AbstractUser model


class UserDetail(AbstractUser):

    userID = models.AutoField(primary_key=True, unique=True)
    username = models.CharField(max_length=128, null=False, unique=True)
    email = models.EmailField(null=False)
    useraddress = models.CharField(max_length=200, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    subscriptionEndAt = models.DateTimeField(
        default=datetime.now()+timedelta(days=7))  # 7 days of trial will automatially added at registration time
    firstName = models.CharField(max_length=128, null=False, unique=True)
    lastName = models.CharField(max_length=128, null=False, unique=True)

    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    isDeleted = models.BooleanField(default=False, null=True)
    isActivated = models.BooleanField(default=True, null=True)
    createdBy = models.CharField(max_length=120)
    updatedBy = models.CharField(max_length=120)

challange2/task/src/apps/payments/models.py
from django.db import models
from src.apps.account.models import UserDetail

#payment details table to save the data of transaction created by user while purchasing subscription
class PaymentDetails(models.Model):

    paymentID = models.AutoField(primary_key=True, unique=True)
    user = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    successed = models.BooleanField(default=False, null=True, blank=True)
    cancelled = models.BooleanField(default=False, null=True, blank=True)
    session_id = models.TextField()

    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    isDeleted = models.BooleanField(default=False, null=True)
    createdBy = models.CharField(max_length=120)
    updatedBy = models.CharField(max_length=120)

#subscription details table to save the data of subscription purchased by user after successful payment
class SubscriptionDetails(models.Model):
    
    subID = models.AutoField(primary_key=True, unique=True)
    user = models.ForeignKey(UserDetail, on_delete=models.CASCADE)
    status = models.CharField(max_length=120)
    subscriptionEndDate = models.DateTimeField(auto_now_add=True)

    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    isDeleted = models.BooleanField(default=False, null=True)
    createdBy = models.CharField(max_length=120)
    updatedBy = models.CharField(max_length=120)

challange2/task/src/apps/account/forms.py
from django_registration.forms import RegistrationForm
from .models import UserDetail

# custom form for user register model
class CustomUserForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = UserDetail
        #desired fields to be taken while user registers
        fields = ["username", "email","firstName","lastName"]

challange2/task/src/apps/account/views.py
from datetime import timedelta
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.contrib.auth.views import LoginView
from django.utils import timezone
from django.contrib.auth import authenticate
from src.apps.account.models import UserDetail
from django.shortcuts import redirect
from django.utils.timezone import localtime


# function to get userdetail from UserDetail table
def get_user_details(uname):
    user = UserDetail.objects.get(username=uname)
    # check condion to know about trial status
    if (user.createdAt + timedelta(days=7)) > timezone.now():
        expired = "Running"
    else:
        expired = "Ended"
    return {"user": user, "expired": expired, "sub_expired": user.subscriptionEndAt}


# profile view for user 's profile
# It will render at successfull registration and login
class ProfileView(TemplateView, DetailView):
    modal = UserDetail
    # view's renderer function for get request

    def get(self, request, *args, **kwargs):
        user = request.user
        details = get_user_details(user)
        return render(request, 'templates/profile.html', details)


# custom lgin view to over ride django registration's LoginView
class CustomLoginView(LoginView):

    def post(self, request, *args, **kwargs):
        password = request.POST.get("password")
        username = request.POST.get("username")
        # authenticate user using password and username
        user = authenticate(username=username, password=password)
        if user:
            return redirect("/accounts/profile/")
        else:
            return render(request, "templates/error.html")

challange2/task/src/apps/payments/views.py
from datetime import timedelta
from django.http import HttpResponse
from django.shortcuts import redirect
import stripe
import os
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from dotenv import load_dotenv
from src.apps.account.models import UserDetail
from src.apps.payments.models import PaymentDetails, SubscriptionDetails

load_dotenv()


# stripe home page
class StripePurchasePage(TemplateView):
    template_name = 'templates/home.html'


# cancellation page render for stripe payment cancel condition
class CancellationConfirmed(TemplateView):
    template_name = 'templates/cancellation_confirmed.html'


# success page render for stripe payment success condition
class SuccessView(TemplateView):
    template_name = 'templates/success.html'

    def get(self, request, *args, **kwargs):
        session_id = request.GET["session_id"]
        payment_obj = PaymentDetails.objects.get(session_id=session_id)
        payment_obj.successed = True
        payment_obj.save()
        user_obj = UserDetail.objects.get(username=request.user)
        sub_end_date = user_obj.subscriptionEndAt + timedelta(days=30)
        user_obj.subscriptionEndAt = sub_end_date
        user_obj.save()
        try:
            sub_obj = SubscriptionDetails.objects.get(user=request.user)
            sub_obj.subscriptionEndDate = sub_end_date
            sub_obj.save()
        except:
            sub_obj = SubscriptionDetails.objects.create(
                user=request.user,
                status="RUNNING",
                subscriptionEndDate=sub_end_date
            )
            sub_obj.save()
        return redirect("/accounts/profile/")


# cancel page render for stripe payment cancel condition
class CancelledView(TemplateView):
    template_name = 'templates/cancelled.html'

    def get(self, request, *args, **kwargs):
        payment_obj = PaymentDetails.objects.filter(
            user=request.user).order_by("createdAt")[0]
        payment_obj.cancelled = True
        payment_obj.save()
        return redirect("/accounts/profile/")


# stripe config view function
@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': os.getenv(
            "STRIPE_PUBLISHABLE_KEY", default="")}
        return JsonResponse(stripe_config, safe=False)


# cancel subscription function
@csrf_exempt
def cancel_sub(request):
    try:
        user_obj = UserDetail.objects.get(username=request.user)
        sub_obj = SubscriptionDetails.objects.get(user=request.user)
        date = user_obj.createdAt + timedelta(days=7)
        sub_obj.subscriptionEndDate = date
        sub_obj.save()
        user_obj.subscriptionEndAt = date
        user_obj.save()
    except Exception as e:
        print(e)
    return redirect("/stripe/cancellation_confirmed/")


# Stripe checkout session function
@csrf_exempt
def create_checkout_session(request):
    if request.method == 'GET':
        domain_url = 'http://localhost:8000/'
        stripe.api_key = os.getenv("STRIPE_SECRET_KEY", default="")
        try:
            user = UserDetail.objects.get(username=request.user)
            checkout_session = stripe.checkout.Session.create(
                success_url=domain_url +
                'stripe/success?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=domain_url + 'stripe/cancelled/',
                payment_method_types=['card'],
                mode='payment',
                line_items=[
                    {
                        'name': 'Trial Subscription',
                        'quantity': 1,
                        'currency': 'inr',
                        'amount': '350000',
                    }
                ]
            )
            payment = PaymentDetails.objects.create(
                user=user, session_id=checkout_session['id'])
            payment.save()
            return JsonResponse({'sessionId': checkout_session['id']})
        except Exception as e:
            return JsonResponse({'error': str(e)})


# Stripe webhook
# first start listening command in terminal "stripe listen --forward-to localhost:8000/webhook/""
@csrf_exempt
def stripe_webhook(request):
    stripe.api_key = os.getenv("STRIPE_SECRET_KEY", default="")
    endpoint_secret = os.getenv("STRIPE_ENDPOINT_SECRET", default="")
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        print("Payment was successful.")
        # TODO: run some custom code here

    return HttpResponse(status=200)

challange2/task/src/templates/cancellation_confirmed.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cancelled</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <center> Subscription cancelled successfully </center>
      <div class="container">
        <a
          class="button is-primary"
          href = "/accounts/profile/"
          id="cancelSubBtn"
        >
          Back to profile
      </a>
      </div>
    </div>
  </section>
  </body>
</html>

challange2/task/src/templates/cancelled.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Cancelled</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
    ></script>
  </head>
  <body>
    <section class="section">
      <div class="container">
        <p>Your payment was cancelled.</p>
      </div>
    </section>
  </body>
</html>

challange2/task/src/templates/error.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error occured</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <center> Error occured </center>
    </div>
  </section>
  </body>
</html>

challange2/task/src/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Subscription purchase</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'main.js' %}"></script>
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
    ></script>
  </head>
  <body>
    <section class="section">
      <div class="container">
        <button class="button is-primary" id="submitBtn">
          Purchase subscription
        </button>
      </div>
    </section>
  </body>
</html>

challange2/task/src/templates/profile.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Profile</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'main.js' %}"></script>
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
    ></script>
  </head>
  <body>
    <section class="section">
      <div class="container">
        <p><strong>Username</strong> - {{user.username}}</p>
        <p><strong>First Name</strong> - {{user.firstName}}</p>
        <p><strong>Last Name</strong> - {{user.lastName}}</p>
        <p><strong>Free trial status</strong> - {{expired}}</p>
        <p><strong>Subscription expiration date</strong> - {{sub_expired}}</p>
      </div>
    </section>
    <div class="container">
      <button class="button is-primary" id="submitBtn">
        Purchase subscription
      </button>
      <a
        class="button is-danger"
        {% comment %} action="{% url 'payments:cancel_sub' %}" {% endcomment %}
        href = "/stripe/cancel_sub/"
        id="cancelSubBtn"
      >
        cancel subscription
    </a>
    </div>
  </body>
</html>

challange2/task/src/templates/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Subscription Purchase</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
    <script
      defer
      src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
    ></script>
  </head>
  <body>
    <section class="section">
      <div class="container">
        <p>Your payment succeeded.</p>
      </div>
    </section>
  </body>
</html>